backend:
  name: github
  repo: makinacorpus/ortho44-2018

media_folder: static/img
public_folder: /img

slug:
  encoding: "ascii"
  clean_accents: true

collections:

  - name: "poi"
    label: "Point of interest"
    folder: "/src/pages/poi"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "poi"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Latitude", name: "lat", widget: "number", valueType: "float", min: -90, max: 90, required: false}
      - {label: "Longitude", name: "lng", widget: "number", valueType: "float", min: -180, max: 360, required: false}
      - {label: "Marker", name: "marker_type", widget: "select", options: ["default", "custom1"]}
      - {label: "Main picture", name: "picture", widget: "image", required: false}
      - {label: "Promote", name: "promote", widget: "boolean", default: false}
      - {label: "Link", name: "link", widget: "string", required: false}
